dbc_files:
  - path: "./CanNetworks2024/system_can.dbc"
    channel_mask: ONE
  - path: "./CanNetworks2024/vehicle_dynamics.dbc"
    channel_mask: TWO
  - path: "./CanNetworks2024/tightverter_front.dbc"
    channel_mask: THREE
  - path: "./CanNetworks2024/tightverter_rear.dbc"
    channel_mask: FOUR
  - path: "./CanNetworks2024/ams_can.dbc"
    channel_mask: FIVE
  # Add more DBC files and channel masks as needed
