inputfilename: 'E:/LOG00000.KMF'
resultDir: "C:/results/"
archiveDir: "C:/LogArchive"

locations: [
        "FahrschuleFD",
        "Fohnsdorf",
        "Grainbach",
        "Kalwang",
        "Kindberg",
        "Lebring",
        "Ludersdorf",
        "-----------",
        "FSEaster",
        "FSAustria",
        "FSEast",
        "FSAA",
        "FSATA",
        "-----------",
        "OFFICE"
        ]

cars: [
        "Caroline",
        "Valerie",
        ]

dbc_files:
  - relativepath: "\\CanNetworks2024\\system_can.dbc"
    channel_mask: ONE
  - relativepath: "\\CanNetworks2024\\vehicle_dynamics.dbc"
    channel_mask: TWO
  - relativepath: "\\CanNetworks2024\\tightverter_front.dbc"
    channel_mask: THREE
  - relativepath: "\\CanNetworks2024\\tightverter_rear.dbc"
    channel_mask: FOUR
  - relativepath: "\\CanNetworks2024\\ams_can.dbc"
    channel_mask: FIVE
